# Generated by Django 4.2.17 on 2025-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='owners',
        ),
        migrations.AddField(
            model_name='newspost',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='news_attachments/', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='horses/', verbose_name='Фото'),
        ),
    ]
