# Generated by Django 4.2.17 on 2025-06-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_trainer',
        ),
        migrations.AddField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Фото'),
        ),
    ]
