# Generated by Django 4.2.17 on 2025-06-20 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trainer_options_remove_trainer_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z0-9\\s\\-\\.\\,!?]+$', 'Описание может содержать только буквы, цифры, пробелы, дефисы, точки, запятые, восклицательные и вопросительные знаки')], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z0-9\\s\\-]+$', 'Имя лошади может содержать только буквы, цифры, пробелы и дефисы')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='horsetrainerrelation',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z0-9\\s\\-\\.\\,!?]+$', 'Заметки могут содержать только буквы, цифры, пробелы, дефисы, точки, запятые, восклицательные и вопросительные знаки')], verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, 'Цена должна быть больше 0'), django.core.validators.MaxValueValidator(999999.99, 'Цена не может превышать 999999.99')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Сумма должна быть больше 0'), django.core.validators.MaxValueValidator(99999999.99, 'Сумма не может превышать 99999999.99')], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z0-9\\s\\-\\.\\,]+$', 'Назначение может содержать только буквы, цифры, пробелы, дефисы, точки и запятые')], verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\-_]+$', 'ID транзакции может содержать только буквы, цифры, дефисы и подчеркивания')], verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='stable',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Вместимость должна быть не менее 1'), django.core.validators.MaxValueValidator(1000, 'Вместимость не может превышать 1000')], verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='stable',
            name='location',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z0-9\\s\\-\\.\\,]+$', 'Местоположение может содержать только буквы, цифры, пробелы, дефисы, точки и запятые')], verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='stable',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z0-9\\s\\-\\.]+$', 'Название может содержать только буквы, цифры, пробелы, дефисы и точки')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='bio',
            field=models.TextField(validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z0-9\\s\\-\\.\\,!?]+$', 'Биография может содержать только буквы, цифры, пробелы, дефисы, точки, запятые, восклицательные и вопросительные знаки')], verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience_years',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Опыт не может быть отрицательным'), django.core.validators.MaxValueValidator(50, 'Опыт не может превышать 50 лет')], verbose_name='Опыт (лет)'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z\\s]+$', 'Имя может содержать только буквы и пробелы')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z\\s]+$', 'Фамилия может содержать только буквы и пробелы')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z0-9\\s\\-\\.\\,]+$', 'Адрес может содержать только буквы, цифры, пробелы, дефисы, точки и запятые')], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-\\(\\)]+$', 'Телефон может содержать только цифры, пробелы, дефисы, скобки и знак +')], verbose_name='Телефон'),
        ),
    ]
