# Generated by Django 4.2.17 on 2025-06-21 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_horse_description_alter_horse_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s\\-]+$', 'Английское имя может содержать только латинские буквы, цифры, пробелы и дефисы')], verbose_name='Имя (англ.)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s\\-\\.\\,!?]+$', 'Английский заголовок может содержать только латинские буквы, цифры, пробелы, дефисы, точки, запятые, восклицательные и вопросительные знаки')], verbose_name='Заголовок (англ.)'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Английское имя может содержать только латинские буквы и пробелы')], verbose_name='Имя (англ.)'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Английская фамилия может содержать только латинские буквы и пробелы')], verbose_name='Фамилия (англ.)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=models.TextField(validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z0-9\\s\\-\\.\\,!?<>/]+$', 'Контент может содержать только буквы, цифры, пробелы, дефисы, точки, запятые, восклицательные и вопросительные знаки, а также HTML теги')], verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z0-9\\s\\-\\.\\,!?]+$', 'Заголовок может содержать только буквы, цифры, пробелы, дефисы, точки, запятые, восклицательные и вопросительные знаки')], verbose_name='Заголовок'),
        ),
    ]
