# Generated by Django 4.2.17 on 2025-06-23 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_horse_name_en_newspost_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date', models.DateTimeField(verbose_name='Дата проведения экзамена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/', verbose_name='Задание (картинка)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('users', models.ManyToManyField(related_name='afexams', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['-date'],
            },
        ),
    ]
